name: Build ReGinkgo Kernel (Script Based)

on:
  workflow_dispatch: # Tombol manual untuk menjalankan build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Download Source Code Kernel (Repo ini)
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: kernel_src

      # 2. Install Aplikasi Dasar Sistem
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git curl wget python3 make gcc g++ \
            libncurses5-dev xz-utils libssl-dev bc flex \
            libelf-dev bison zip unzip zlib1g-dev \
            libfdt-dev device-tree-compiler cpio \
            openssh-client repo

      # 3. Jalankan Script build_reginkgo.sh
      - name: Run Build Script
        run: |
          cd kernel_src

          # Pastikan script punya izin eksekusi
          chmod +x build_reginkgo.sh

          # Jalankan scriptnya
          ./build_reginkgo.sh ginkgo k

      # 4. Upload Hasil Build
      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReGinkgo-Kernel-Result
          path: |
            kernel_src/*.zip
            kernel_src/AnyKernel3/*.zip
            /home/runner/AnyKernel3/*.zip
            /home/runner/workflow/*.zip
